version: '3'

services:
  slowdash:
    image: slowdash
    volumes:
      - .:/project
    ports:
      - "18881:18881"

  testdata:
    image: slowproj/slowdash
    volumes:
      - .:/project
    command: python /slowdash/utils/generate-testdata.py --db-url=csv:///SlowTestData.d
