services:

  slowdash:
    image: slowdash-honeybee
    build:
      context: https://github.com/slowproj/slowdash.git#develop
      args:
        BASE_IMAGE: honeybee
    ports:
      - "18881:18881"
    volumes:
      - ./slowdash.d:/project
    environment:
      - HONEYBEE_BIN=/honeybee/bin
      - HONEYBEE_CONFIG=/honeybee/SensorTable/SensorTable_CCA.ktf
      - DRIPLINE_DB_URL=postgresql://p8_db_user:dripline@host.docker.internal:5431/p8_sc_db
